### ISSUE TITLE
PA Review: Comment

### ISSUE THREAD

**Issue by locphan2207** [locphan2207/Food-Stories#9]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds
***
**Others:**
- [x] Users can upload their food photos into their comment.

**Comment by anastassia-b** [comment]
This is awesome! Functionality is perfect, and this is beautiful work, I love all the ui features. Nice implementation of replies to comments. Some feedback:

- [ ] When I reply to a comment, the second `.comment-body` is small, it does not go to the end. 
- [ ] Give `.comment-body-input` a `padding-left: 20px` so that the cursor doesn't start close to the box. 
- [ ] Tan Loc Master doesn't have an image on heroku.
- [ ] Add a few comment seeds by different users. You can write a function in your `seeds.rb` file that will randomly seed for you, even with the same phrase/randomized.

**Comment by locphan2207** [comment]
Done

**Comment by anastassia-b** [comment]
Awesome!
